# Travis-CI.org build script

# "trusty" is Ubuntu 14.04.5 LTS
# gcc 4.8.4

# According to https://github.com/uclouvain/openjpeg/blob/master/.travis.yml
# "sudo: yes" and "dist: trusty" give us a worker with the AVX2 instruction set
# (2018-04-08 this does not seem to be the case)
#sudo: yes
#dist: trusty

os: osx

# Formerly:
# use containerized infrastructure (for faster startup; no sudo)
#sudo: false
#dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lz4 yaml-cpp jsoncpp; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fftw --without-fortran; fi
    # boost: already installed
    # fftw: problematic

before_script:
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cat /proc/cpuinfo; fi

    - pip2 install --user cpp-coveralls
    - pip2 install --user Cython

    # for cython
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=${PATH}:~/Library/Python/2.7/bin; fi
    - which cython

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install numpy; fi

    - find /usr/local/lib/python2.7/

    - BUILD_DIR=$(pwd)

    - cd
    - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.1.0/msgpack-2.1.0.tar.gz
    - tar xzf msgpack-2.1.0.tar.gz
    - export MSGPACK_INC_DIR=$(pwd)/msgpack-2.1.0/include

    - cd
    - ls
    # We cache the "libzmq" directory -- does it exist & is it a valid git repo?
    - if [ -d "libzmq" ]; then (cd libzmq && git describe) || rm -R libzmq; fi
    - if [ ! -d "libzmq" ]; then (git clone https://github.com/zeromq/libzmq.git && cd libzmq && git checkout v4.2.1 && ./autogen.sh); fi
    - cd libzmq
    - ./configure --prefix=${HOME}/zmq --disable-perf --disable-curve -disable-curve-keygen --without-docs
    - make
    - make install
    - export ZMQ_INC_DIR=~/zmq/include
    - export ZMQ_LIB_DIR=~/zmq/lib
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ZMQ_LIB_DIR}
    - export PKG_CONFIG_DIR=${PKG_CONFIG_DIR}:${ZMQ_LIB_DIR}/pkgconfig

    - pip2 install --user pyzmq
    - pip2 install --user msgpack-python

    - cd
    - wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
    - cp zmq.hpp $ZMQ_INC_DIR

    # Cached hdf5 source code install
    # - cd
    # - if [ -d "hdf5" ]; then (cd hdf5 && make all install > hdf5.log 2>&1) || rm -R hdf5; fi
    # - if [ ! -d "hdf5" ]; then (wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.20/src/hdf5-1.8.20.tar.gz && tar xzf hdf5-1.8.20.tar.gz && mv hdf5-1.8.20 hdf5 && cd hdf5 && ./configure --prefix=$HOME/chime --enable-cxx && make all install > hdf5.log 2>&1); fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install hdf5@1.8; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install hdf5; fi

    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:~/chime/lib

    # Environment variables respected by (some) CHIME Makefile.local files
    - export LIBDIR=~/chime/lib
    - export INCDIR=~/chime/include
    - export BINDIR=~/chime/bin
    - export HAVE_PSRFITS=n
    - export HAVE_CH_FRB_IO=y
    - export HAVE_BONSAI=y
    - export PYDIR=~/chime/lib/python2.7/site-packages
    - export PYTHON_INCDIR=/usr/include/python2.7
    #- export NUMPY_INCDIR=/usr/lib/python2.7/dist-packages/numpy/core/include
    - which python
    - which python2
    - export NUMPY_INCDIR=$(python -c "import numpy; print(numpy.get_include())")
    - export JSONCPP_INC_DIR=/usr/include/jsoncpp
    - export PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7/dist-packages

    - cd
    - git clone https://github.com/CHIMEFRB/ch_frb_io.git
    - cd ch_frb_io
    - git checkout rpc_cleanup
    - ln -s site/Makefile.local.travis Makefile.local
    - pwd
    - make
    - make install

    - cd
    - git clone https://github.com/kmsmith137/simd_helpers.git
    - cd simd_helpers
    - ln -s site/Makefile.local.norootprivs Makefile.local
    - make install

    - cd
    - git clone https://github.com/kmsmith137/simpulse.git
    - cd simpulse
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

    - cd
    - git clone https://github.com/kmsmith137/sp_hdf5.git
    - cd sp_hdf5
    - ln -s site/Makefile.local.linux Makefile.local
    - make install
    - cd
    - mv include/* chime/include/

    - cd
    #- git clone https://github.com/kmsmith137/rf_kernels.git
    - git clone https://github.com/dstndstn/rf_kernels.git
    - cd rf_kernels
    ###
    - git checkout travis
    - ln -s site/Makefile.local.travis Makefile.local
    - make install

    - cd
    ###- git clone https://github.com/CHIMEFRB/bonsai.git
    ###- cd bonsai
    - mkdir bonsai
    #- wget -O bonsai.tgz http://broiler.astrometry.net/~dstn/temp/bonsai-master-2017-04-10.tgz
    #- wget -O bonsai.tgz http://broiler.astrometry.net/~dstn/temp/bonsai-l1-prerelease.tgz
    - wget -O bonsai.tgz http://broiler.astrometry.net/~dstn/temp/bonsai-15_devel.tgz
    - tar xzf bonsai.tgz
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

    - cd
    - git clone https://github.com/kmsmith137/rf_pipelines.git
    - cd rf_pipelines
    #- git checkout l1_prerelease2
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

script:
    - pwd
    - cd $BUILD_DIR
    - pwd
    - ln -s site/Makefile.local.travis Makefile.local
    # - ls ~/chime/lib
    # - ls ~/chime/include
    # - ls ~/lib
    # - ls ~/include
    # - nm -CD ~/chime/lib/librf_pipelines.so
    - make COVERAGE=yes OPTIMIZE=no
    # run some, ahem, unit tests...
    - ./test-l1-rpc &
    - sleep 3
    - python rpc_client.py --shutdown 5555
    - wait
    
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

addons:
  apt:
    packages:
      - liblz4-dev
      - libyaml-cpp-dev
      - libboost-dev
      - libjsoncpp-dev  # for rf_pipelines
      - python-numpy    # for rpc_client.py and simpulse
      - libfftw3-dev    # for simpulse

# Versions in trusty are too old:
#      - libzmq-dev (2.1 vs current = 4.2.0)
#      - libhdf5-serial-dev   # need newer version for sp_hdf5
#      - cython          # for simpulse  -- need a version newer than 0.20.1 ?
# see ch_frb_io re: libmsgpack-dev

cache:
  directories:
  - $HOME/libzmq
  - $HOME/hdf5
